# Generated by Django 3.2.6 on 2021-08-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_apis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('critical_level', models.CharField(default='low', max_length=5)),
                ('pincode', models.CharField(max_length=6)),
                ('hospital', models.CharField(max_length=70)),
                ('time_slot_start', models.CharField(max_length=20)),
                ('time_slot_end', models.CharField(max_length=20)),
            ],
        ),
    ]
